env:
    MANIFEST: https://github.com/LineageOS/android.git
    MANIFEST_BRANCH: lineage-19.1
    # Not Recommended to Change
    
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: Build
  only_if: $CIRRUS_REPO_OWNER == 'melles1991'
  timeout_in: 6h
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 32G

  env_script:
    - env
    
  Sync_script:
    - bash sync.sh
    
  Build_script:
    - bash build.sh
    
