env:
    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: exodus-build
  only_if: $CIRRUS_REPO_OWNER == 'ExodusOS'
  timeout_in: 60m
  container:
    image: stupidkidaf/kernel_docker:v1
    cpu: 4
    memory: 16G
  env_script:
    - env
  Sync_script:
      - bash sync.sh
  Build_script:
      - bash build.sh
