env:
    MANIFEST: https://github.com/ExodusOS/android.git
    MANIFEST_BRANCH: lineage-19.1
    # Not Recommended to Change
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/ccache/exodus/$device
    J_VAL: 16
    DEVICE: onclite
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: Build
  only_if: $CIRRUS_REPO_OWNER == 'melles1991'
  timeout_in: 4h
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 32G
    volumes:
        - /home/cirrus/exodus:/home/cirrus/exodus
        - /home/cirrus/ccache:/home/cirrus/ccache
        - /home/cirrus/.config:/home/cirrus/.config

  init_script:
    - cd $HOME && sudo apt-get install git -y && git clone https://github.com/CraftRom/scripts && cd scripts && sudo bash setup/android_build_env.sh
  sync_script:
    - set -e
    - branch=squirrel
    - mkdir -p ~/exodus/$branch
    - cd ~/exodus/$branch
    - rm -rf .repo/local_manifests
    - bash -c repo init -u https://github.com/ExodusOS/android.git -b lineage-19.1 || true
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

    - rm -rf sync.log

  build_script:
    - set -e
    - branch=squirrel
    - cd ~/exodus/$branch
    - export CCACHE_DIR=$CCACHE_DIR
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 8G
    - ccache -z
    - . build/envsetup.sh
    - mka cleaninstall
    - breakfast lineage_$DEVICE_START-$TYPE
    
