env:
    MANIFEST: https://github.com/LineageOS/android.git
    MANIFEST_BRANCH: lineage-19.1
    LOCAL_MANIFEST: https://github.com/melles1991/exodus_manifest.git
    LOCAL_BRANCH : lineage-19.1
    DEVICE: onclite
    # Not Recommended to Change
    
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: Build
  only_if: $CIRRUS_REPO_OWNER == 'melles1991'
  timeout_in: 6h
  container:
    image: gcr.io/ci-cd-215716/sonar-enterprise-build:0.0.3
    cluster_name: cirrus-euw3a-cluster
    zone: europe-west3-a
    namespace: default
    cpu: 2.4
    memory: 10Gb
    additional_containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
        port: 1433

  env_script:
    - env
    
  Sync_script:
    - bash sync.sh
    
  Build_script:
    - bash build.sh
    
